kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: dep-pod
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-volume
          mountPath: /var/www/html
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: lc-pvc
          

