kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lc-pvc
  namespace: nginx
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
