apiVersion: v1

kind: Pod

metadata:

  name: todo-pod

  namespace: todo-list

spec:

  containers:

  - name: todo-app

    image: trainwithshubham/django-todo:latest

    ports:

    - containerPort: 8000

